---
server:
  port: 9080

sampleservice:
  ribbon:
    DeploymentContextBasedVipAddresses: sample-hystrix-service
    ReadTimeout: 10000
    MaxAutoRetries: 2

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 1
        sleepWindowInMilliseconds: 5000
    MessageAnnotationHystrixCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 1
        sleepWindowInMilliseconds: 5000
