---
server:
  port: 9080

sampleservice:
  ribbon:
    DeploymentContextBasedVipAddresses: sample-hystrix-service
    ReadTimeout: 10000
    MaxAutoRetries: 2

hystrix:
  command:
    MessageAnnotationHystrixCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        requestVolumeThreshold: 4
        sleepWindowInMilliseconds: 5000
    MessageHystrixCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        requestVolumeThreshold: 4
        sleepWindowInMilliseconds: 5000
