---
server:
  port: 8989


turbine:
  aggregator:
    clusterConfig: SAMPLE-HYSTRIX-AGGREGATE
  appConfig: SAMPLE-HYSTRIX-AGGREGATE,SAMPLE-HYSTRIX-GATEWAY

#turbine:
#  aggregator:
#    clusterConfig: huawei-cloud
#  instanceInsertPort:
#    huawei-cloud: false
#  instanceUrlSuffix:
#    huawei-cloud: /hystrix.stream
#  ConfigPropertyBasedDiscovery:
#    huawei-cloud:
#      instances: localhost:1111,localhost:2222
#

logging:
  level: INFO